name: CI - Compile

on:
  push:
    branches: [master]

jobs:
  build-yocto:
    runs-on: [self-hosted, linux, x64, yocto]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build Yocto Rootfs
        run: |
          ./balena-yocto-scripts/build/barys -m rockchip-px30-evb --shared-downloads /yocto/shared-downloads --shared-sstate /yocto/shared-sstate

      - name: Compress the output images
        run: |
          tar -czvf images.tar.gz -C ./build/tmp/deploy/images/rockchip-px30-evb .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: images
          path: images.tar.gz
          retention-days: 1
